# Generated by Django 5.1.2 on 2024-10-12 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callroom',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='callroom',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
