# Generated by Django 5.1.2 on 2024-10-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_user_options_alter_usertoken_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='main_app_us_user_id_027685_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='User ID'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['id'], name='main_app_us_id_c39bf4_idx'),
        ),
    ]
